/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokemonpro.ventana;

import java.applet.AudioClip;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author aco
 */
public class Login extends javax.swing.JFrame {

    private static Scanner sc;
    private static int intentos;          //Cuenta el no. de intentos y para cerrar el login en 3 intentos
    private static String user, pwd;      //Son para almacenar los datos ingresados para el usuario y el password respectivamente
    
    
   
    
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        rootPane.setDefaultButton(start);
        
        

        
    }

    public static void setIntentos(int intentos) {
        Login.intentos = intentos;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contrasena = new javax.swing.JPasswordField();
        contrasenatext = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        salir2 = new javax.swing.JButton();
        register = new javax.swing.JButton();
        start = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contrasena.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        getContentPane().add(contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 210, 50));

        contrasenatext.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        contrasenatext.setText("Contraseña:");
        getContentPane().add(contrasenatext, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        jLabel2.setText("Entrenador:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        usuario.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 210, 50));

        salir2.setBackground(new java.awt.Color(208, 51, 2));
        salir2.setFont(new java.awt.Font("Ubuntu", 0, 43)); // NOI18N
        salir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemonpro/img/x.png"))); // NOI18N
        salir2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir2ActionPerformed(evt);
            }
        });
        getContentPane().add(salir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 60, 60));

        register.setBackground(new java.awt.Color(55, 158, 233));
        register.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        register.setForeground(new java.awt.Color(254, 254, 254));
        register.setText("REGISTRO ");
        register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        getContentPane().add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 220, 70));

        start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemonpro/img/start.png"))); // NOI18N
        start.setBorderPainted(false);
        start.setContentAreaFilled(false);
        start.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        getContentPane().add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 130, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemonpro/img/IniciarS.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salir2ActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
      
       
       File file = new File("usuarios.txt");
       if(!file.exists())
       {
           try{
               file.createNewFile();
               
           }catch(IOException ex){}
       }
       
       
       
       Registro regis = new Registro();
       regis.setVisible(true);
       this.setVisible(false);
       
    }//GEN-LAST:event_registerActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        
        FileReader fr=null; 
        try {
            int nLineas=0; //Nos permite contar el número de líneas de nuestro archivo bd (Archivo de texto plano que funciona como una base de datos)
            int i=0; //Contador
            String [] usuarios = null; //Arreglo de Strings que nos permite almacenar los datos de usuario 
            String linea; //La linea con la que estamos trabajando
            sc = new Scanner(new File("usuarios.txt"));

            File f = new File("usuarios.txt");
            
            fr = new FileReader(f);
            BufferedReader br = new BufferedReader(fr);
            
            try {
                while((linea=br.readLine())!=null){//Cuenta líneas
                    nLineas++;
                }
            } catch (IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
               
            }finally{
                usuarios=new String[nLineas]; //El tamaño del arreglo
            
            while(sc.hasNextLine()){
                usuarios[i++] = sc.nextLine();//almacenamos una línea en cada posición
            }
            
            
            intentos++;
            
            user = usuario.getText();
            pwd = contrasena.getText();
            
          
            Seguridad s = new Seguridad();
            if((s.validarUsuario(usuarios, user, pwd, intentos)) != false){
                Select selecto = new Select();
                selecto.setVisible(true);
                this.setVisible(false);
                
        }else{
                if(intentos>2){
                 JOptionPane.showMessageDialog(null, "Has intentado muchas veces, vuelva más tarde", "SEGURIDAD", JOptionPane.ERROR_MESSAGE);
                 System.exit(0);
            }
            
                 JOptionPane.showMessageDialog(null, "Usuario y/o contraseña invalidos, llevas "+ intentos + " intentos","INICIO DE SESIÓN", JOptionPane.ERROR_MESSAGE);
                 
            
            }
            }
            
            
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            
        } finally {
            File f = new File("usuarios.txt");
            if(!f.exists()){
            JOptionPane.showMessageDialog(null, "!No hay entrenadores!, dirigete a el botón de Registro", "CONVIERTETE EN EL MEJOR", JOptionPane.INFORMATION_MESSAGE);
            }
            try {
                fr.close();
            } catch (IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        
    }//GEN-LAST:event_startActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contrasena;
    private javax.swing.JLabel contrasenatext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton register;
    private javax.swing.JButton salir2;
    private javax.swing.JButton start;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
