/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokemonpro.ventana;

import java.applet.AudioClip;



/**
 *
 * @author aco
 */
public class Menu extends javax.swing.JFrame {

    AudioClip Sound;
        
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
                
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/pokemonpro/men.wav"));
        Sound.play();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salir = new javax.swing.JButton();
        psalir = new javax.swing.JButton();
        jugar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setBackground(new java.awt.Color(206, 75, 33));
        salir.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        salir.setText("X");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 50, 50));

        psalir.setFont(new java.awt.Font("Ubuntu", 2, 48)); // NOI18N
        psalir.setForeground(new java.awt.Color(115, 46, 46));
        psalir.setText("          SALIR");
        psalir.setAlignmentY(1.0F);
        psalir.setAutoscrolls(true);
        psalir.setBorderPainted(false);
        psalir.setContentAreaFilled(false);
        psalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        psalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psalirActionPerformed(evt);
            }
        });
        getContentPane().add(psalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 370, 130));

        jugar.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        jugar.setForeground(new java.awt.Color(254, 254, 254));
        jugar.setText("           JUGAR");
        jugar.setBorderPainted(false);
        jugar.setContentAreaFilled(false);
        jugar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugarActionPerformed(evt);
            }
        });
        getContentPane().add(jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 380, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemonpro/img/meni.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void psalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_psalirActionPerformed

    private void jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugarActionPerformed
        Login log = new Login();
        log.setVisible(true);
        this.setVisible(false);
        Sound.stop();
    }//GEN-LAST:event_jugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jugar;
    private javax.swing.JButton psalir;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
