/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokemonpro.ventana;

import java.applet.AudioClip;

/**
 *
 * @author aco
 */
public class Nombres extends javax.swing.JFrame {

    AudioClip Sound;
    /**
     * Creates new form Nombres
     */
    public Nombres() {
        initComponents();
        this.setLocationRelativeTo(null);
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/pokemonpro/battle.wav"));
        Sound.play();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1 = new javax.swing.JTextField();
        p2 = new javax.swing.JTextField();
        combat = new javax.swing.JButton();
        sal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p1.setBackground(new java.awt.Color(254, 228, 136));
        p1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        p1.setForeground(new java.awt.Color(153, 76, 0));
        p1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p1.setText("JUGADOR 1");
        p1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(92, 108, 184)));
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 585, 360, 40));

        p2.setBackground(new java.awt.Color(156, 191, 226));
        p2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        p2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p2.setText("JUGADOR 2");
        p2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(198, 124, 36)));
        p2.setSelectionColor(new java.awt.Color(240, 152, 62));
        getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 585, 350, 40));

        combat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemonpro/img/combate.png"))); // NOI18N
        combat.setBorderPainted(false);
        combat.setContentAreaFilled(false);
        combat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combatActionPerformed(evt);
            }
        });
        getContentPane().add(combat, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 640, 310, -1));

        sal.setForeground(new java.awt.Color(148, 148, 148));
        sal.setText("SALIR");
        sal.setBorderPainted(false);
        sal.setContentAreaFilled(false);
        sal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salActionPerformed(evt);
            }
        });
        getContentPane().add(sal, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemonpro/img/combatI.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combatActionPerformed
        Sound.stop();
        Personajes equipo = new Personajes();
        equipo.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_combatActionPerformed

    private void salActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nombres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nombres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nombres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nombres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nombres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton combat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField p1;
    private javax.swing.JTextField p2;
    private javax.swing.JButton sal;
    // End of variables declaration//GEN-END:variables
}
