/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokemonpro.ventana;

import java.applet.AudioClip;

/**
 *
 * @author aco
 */
public class Personajes extends javax.swing.JFrame {

    /**
     * Creates new form Personajes
     */
    AudioClip Sound;
    
    public Personajes() {
        initComponents();
        this.setLocationRelativeTo(null);
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/pokemonpro/ready.wav"));
        Sound.play();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JButton();
        vMew = new javax.swing.JButton();
        vPikachu = new javax.swing.JButton();
        vPonyta = new javax.swing.JButton();
        vNidorina = new javax.swing.JButton();
        vVulpix = new javax.swing.JButton();
        vsquirtle = new javax.swing.JButton();
        vArcaine = new javax.swing.JButton();
        vMachamp = new javax.swing.JButton();
        vArbok = new javax.swing.JButton();
        vVoltorb = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(185, 185, 185));
        exit.setText("SALIR");
        exit.setBorderPainted(false);
        exit.setContentAreaFilled(false);
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 0, 130, 40));

        vMew.setBorderPainted(false);
        vMew.setContentAreaFilled(false);
        vMew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vMew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vMewActionPerformed(evt);
            }
        });
        getContentPane().add(vMew, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 58, 120, 160));

        vPikachu.setBorderPainted(false);
        vPikachu.setContentAreaFilled(false);
        vPikachu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vPikachu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vPikachuActionPerformed(evt);
            }
        });
        getContentPane().add(vPikachu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 190, 140));

        vPonyta.setBorderPainted(false);
        vPonyta.setContentAreaFilled(false);
        vPonyta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vPonyta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vPonytaActionPerformed(evt);
            }
        });
        getContentPane().add(vPonyta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 160, 180));

        vNidorina.setBorderPainted(false);
        vNidorina.setContentAreaFilled(false);
        vNidorina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vNidorina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vNidorinaActionPerformed(evt);
            }
        });
        getContentPane().add(vNidorina, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 200, 270));

        vVulpix.setBorderPainted(false);
        vVulpix.setContentAreaFilled(false);
        vVulpix.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vVulpix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vVulpixActionPerformed(evt);
            }
        });
        getContentPane().add(vVulpix, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 330, 220));

        vsquirtle.setBorderPainted(false);
        vsquirtle.setContentAreaFilled(false);
        vsquirtle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vsquirtle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vsquirtleActionPerformed(evt);
            }
        });
        getContentPane().add(vsquirtle, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 470, 240, 230));

        vArcaine.setBorderPainted(false);
        vArcaine.setContentAreaFilled(false);
        vArcaine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vArcaine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vArcaineActionPerformed(evt);
            }
        });
        getContentPane().add(vArcaine, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 230, 160));

        vMachamp.setBorderPainted(false);
        vMachamp.setContentAreaFilled(false);
        vMachamp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vMachamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vMachampActionPerformed(evt);
            }
        });
        getContentPane().add(vMachamp, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 200, 170));

        vArbok.setBorderPainted(false);
        vArbok.setContentAreaFilled(false);
        vArbok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vArbok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vArbokActionPerformed(evt);
            }
        });
        getContentPane().add(vArbok, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, 160, 140));

        vVoltorb.setBorderPainted(false);
        vVoltorb.setContentAreaFilled(false);
        vVoltorb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vVoltorb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vVoltorbActionPerformed(evt);
            }
        });
        getContentPane().add(vVoltorb, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 160, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemonpro/img/Personajes.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void vPikachuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vPikachuActionPerformed
        AudioClip pika;
        pika = java.applet.Applet.newAudioClip(getClass().getResource("/pokemonpro/pika.wav"));
        pika.play();
    }//GEN-LAST:event_vPikachuActionPerformed

    private void vMewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vMewActionPerformed
        AudioClip mew;
        mew = java.applet.Applet.newAudioClip(getClass().getResource("/pokemonpro/mew.wav"));
        mew.play();
    }//GEN-LAST:event_vMewActionPerformed

    private void vVoltorbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vVoltorbActionPerformed
       AudioClip volt;
        volt = java.applet.Applet.newAudioClip(getClass().getResource("/pokemonpro/volt.wav"));
        volt.play();
    }//GEN-LAST:event_vVoltorbActionPerformed

    private void vVulpixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vVulpixActionPerformed
        AudioClip vul;
        vul = java.applet.Applet.newAudioClip(getClass().getResource("/pokemonpro/vul.wav"));
        vul.play();
    }//GEN-LAST:event_vVulpixActionPerformed

    private void vsquirtleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vsquirtleActionPerformed
        AudioClip squir;
        squir = java.applet.Applet.newAudioClip(getClass().getResource("/pokemonpro/sq.wav"));
        squir.play();
    }//GEN-LAST:event_vsquirtleActionPerformed

    private void vArbokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vArbokActionPerformed
        AudioClip ar;
        ar = java.applet.Applet.newAudioClip(getClass().getResource("/pokemonpro/ar.wav"));
        ar.play();
    }//GEN-LAST:event_vArbokActionPerformed

    private void vMachampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vMachampActionPerformed
        AudioClip mach;
        mach = java.applet.Applet.newAudioClip(getClass().getResource("/pokemonpro/mach.wav"));
        mach.play();
    }//GEN-LAST:event_vMachampActionPerformed

    private void vArcaineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vArcaineActionPerformed
        AudioClip arca;
        arca = java.applet.Applet.newAudioClip(getClass().getResource("/pokemonpro/arca.wav"));
        arca.play();
    }//GEN-LAST:event_vArcaineActionPerformed

    private void vPonytaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vPonytaActionPerformed
        AudioClip pon;
        pon = java.applet.Applet.newAudioClip(getClass().getResource("/pokemonpro/pon.wav"));
        pon.play();
    }//GEN-LAST:event_vPonytaActionPerformed

    private void vNidorinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vNidorinaActionPerformed
        // TODO add your handling code here:
        AudioClip ni;
        ni = java.applet.Applet.newAudioClip(getClass().getResource("/pokemonpro/ni.wav"));
        ni.play();
    }//GEN-LAST:event_vNidorinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personajes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton vArbok;
    private javax.swing.JButton vArcaine;
    private javax.swing.JButton vMachamp;
    private javax.swing.JButton vMew;
    private javax.swing.JButton vNidorina;
    private javax.swing.JButton vPikachu;
    private javax.swing.JButton vPonyta;
    private javax.swing.JButton vVoltorb;
    private javax.swing.JButton vVulpix;
    private javax.swing.JButton vsquirtle;
    // End of variables declaration//GEN-END:variables
}
