
package pokemonpro.ventana;

import java.applet.AudioClip;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;

/**
 *
 * @author aco
 */
public class Registro extends javax.swing.JFrame {

    
     AudioClip Sound;
     private static String name, clav;

    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/pokemonpro/opening.wav"));
        Sound.play();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nusu = new javax.swing.JTextField();
        npwd = new javax.swing.JPasswordField();
        frase = new javax.swing.JTextField();
        acepto = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nusu.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        getContentPane().add(nusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 270, 40));

        npwd.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        getContentPane().add(npwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 270, 40));
        getContentPane().add(frase, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 270, 40));

        acepto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemonpro/img/acepto.png"))); // NOI18N
        acepto.setBorderPainted(false);
        acepto.setContentAreaFilled(false);
        acepto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        acepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptoActionPerformed(evt);
            }
        });
        getContentPane().add(acepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemonpro/img/x.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, -1, -1));

        atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemonpro/img/atras.png"))); // NOI18N
        atras.setBorderPainted(false);
        atras.setContentAreaFilled(false);
        atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        getContentPane().add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemonpro/img/RegistroI.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptoActionPerformed
        File f;
        FileWriter w;
        BufferedWriter bw;
        PrintWriter wr;
        
        try{
            f=new File("usuarios.txt");
            w=new FileWriter(f,true);
            bw=new BufferedWriter(w);
            wr=new PrintWriter(bw);
            
            name=nusu.getText();
            clav=npwd.getText();
            
            wr.println(name);
            wr.println(clav);
            
            wr.close();
            bw.close();
            
        }catch (Exception e){
            
        }
        Sound.stop();
        Login ses = new Login();
        ses.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_aceptoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        Login logi = new Login();
        logi.setVisible(true);
        this.setVisible(false);
        Sound.stop();
    }//GEN-LAST:event_atrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acepto;
    private javax.swing.JButton atras;
    private javax.swing.JTextField frase;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField npwd;
    private javax.swing.JTextField nusu;
    // End of variables declaration//GEN-END:variables
}
