/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokemonpro.ventana;

import java.applet.AudioClip;

/**
 *
 * @author aco
 */
public class Select extends javax.swing.JFrame {

    
    AudioClip Sound;
    /**
     * Creates new form Select
     */
    public Select() {
        initComponents();
        this.setLocationRelativeTo(null);
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/pokemonpro/fuego.wav"));
        Sound.play();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salir = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        creador = new javax.swing.JButton();
        unidor = new javax.swing.JButton();
        sele = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemonpro/img/x.png"))); // NOI18N
        salir.setBorderPainted(false);
        salir.setContentAreaFilled(false);
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 620, -1, -1));

        atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemonpro/img/atras.png"))); // NOI18N
        atras.setBorderPainted(false);
        atras.setContentAreaFilled(false);
        atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        getContentPane().add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        creador.setBorderPainted(false);
        creador.setContentAreaFilled(false);
        creador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        creador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creadorActionPerformed(evt);
            }
        });
        getContentPane().add(creador, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 280, 190));

        unidor.setBorderPainted(false);
        unidor.setContentAreaFilled(false);
        unidor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(unidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 300, 190));

        sele.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemonpro/img/modo.jpg"))); // NOI18N
        getContentPane().add(sele, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        Sound.stop();
        Login lolo = new Login();
        lolo.setVisible(true);
        this.setVisible(false);
    
    }//GEN-LAST:event_atrasActionPerformed

    private void creadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creadorActionPerformed
        Sound.stop();
        Creador crea = new Creador();
        crea.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_creadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Select().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JButton creador;
    private javax.swing.JButton salir;
    private javax.swing.JLabel sele;
    private javax.swing.JButton unidor;
    // End of variables declaration//GEN-END:variables
}
